services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  ### Declare services ###
  App\Application\:
    resource: '../src/Application/**'
    exclude: '../src/Application/{File}'
    tags: [ 'controller.service_arguments' ]

  App\Infrastructure\:
    resource: '../src/Infrastructure/*'

  App\Domain\:
    resource: '../src/Domain/*'
    exclude:
      - '../src/Domain/*/{Event,Exception,Request,Response,Dto,Message}'
      - '../src/Domain/Visit/Visit.php'

  App\Infrastructure\EventListener\CorsListener:
    tags:
      - { name: kernel.event_listener, event: kernel.response, priority: 255 }